server:
  port: 8081

spring:
  application:
    name: authenticator

  # Cloud Configuration
  cloud:
    gateway:
      mvc:
        routes:
          - id: profile
            uri: lb://profile
            predicates:
              - Path=/profile/**

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        format_sql: true

  # Liquibase Configuration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  # SQL Initialization
  sql:
    init:
      mode: always

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# SpringDoc API Docs
springdoc:
  api-docs:
    path: /api-docs
